name: notes_ddd_app
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  freezed_annotation: ^0.11.0+1
  dartz: ^0.9.1
  flutter_bloc: ^6.0.1
  firebase_core: ^0.5.0
  firebase_auth: ^0.18.0+1
  google_sign_in: ^4.5.1
  get_it: ^4.0.4
  injectable: ^1.0.4
  cloud_firestore: ^0.14.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^4.1.1
  freezed: ^0.11.5
  lint: ^1.2.0
  build_runner: ^1.10.1
  injectable_generator: ^1.0.4

flutter:
  uses-material-design: true

